### ISSUE TITLE
Linux compile

### ISSUE THREAD

**Issue by dubanoze** [JiapengLi/lorawan-parser#1]
Hello.
dd@alm-01:~/lora/server/lorawan-parser# make
Making all in lib
make[1]: Entering directory `/home/dubanoze/lora/server/lorawan-parser/lib'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/home/dubanoze/lora/server/lorawan-parser/lib'
Making all in lw
make[1]: Entering directory`/home/dubanoze/lora/server/lorawan-parser/lw'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory`/home/dubanoze/lora/server/lorawan-parser/lw'
Making all in util/parser
make[1]: Entering directory `/home/dubanoze/lora/server/lorawan-parser/util/parser'
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -std=gnu99  -g -O2   -o lwp main.o config.o ../../lib/lib.la ../../lw/liblorawan.la 
libtool: link: gcc -std=gnu99 -g -O2 -o lwp main.o config.o  ../../lib/.libs/lib.a ../../lw/.libs/liblorawan.a
../../lw/.libs/liblorawan.a(lorawan.o): In function`lw_maccmd':
/home/dubanoze/lora/server/lorawan-parser/lw/lorawan.c:976: undefined reference to `pow'
/home/dubanoze/lora/server/lorawan-parser/lw/lorawan.c:993: undefined reference to`pow'
/home/dubanoze/lora/server/lorawan-parser/lw/lorawan.c:949: undefined reference to `pow'
collect2: error: ld returned 1 exit status
make[1]: *** [lwp] Error 1
make[1]: Leaving directory`/home/dubanoze/lora/server/lorawan-parser/util/parser'
make: **\* [all-recursive] Error 1

**Comment by JiapengLi** [comment]
math library missing issue. fixed.
