### ISSUE TITLE
Cannot parse decoded packets from gr-lora

### ISSUE THREAD

**Issue by stefanidisgeorge** [JiapengLi/lorawan-parser#9]
Hi, I am trying to parse packets received by gr-lora in Gnuradio.

The Packets are exported on Terminal and then I copy them  and use them as parameter in the parser.

./lwp -p "67 f5 03 96 95 27 7e b8 83 42 8c 12 0e 8e f3 05 0e 79 e3 07 9d 79 34 72 cb 20 63 c2 71 dd c6 09 20 22 04 29 8d 32 5d 24 20 bf 5e eb 62 97 35 0c bb 79 79 d1 0d 8b 0e 80 10 ba 7c 12 2e 75 47 7e 4b d7 93 bb 2e 06 b1 b2 48 9c 80 39 30 61 10 1c f2 71 de 9d d8 95 7c d2 75 eb 5a a0 df 72 66 ba a4 af 58 b0 e5 f3 b7 1e 1c be f9 33 e7 e4 db b7 7f d7 ad 7e f5 6b 11 a8 e3" 

but I get an error:
DATA MESSAGE PARSER error(-15)

**Comment by JiapengLi** [comment]
Dear sir, 
the payload seems not to be a LoRaWAN frame. 0x67 is invalid header .
